apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    build.appstudio.openshift.io/application: test-psturc
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: build-suite-test-component-git-source-yyrwvypcex
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: build-suite-test-component-git-source-yyrwvypcex
  namespace: psturc
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: build-suite-test-component-git-source-yyrwvypcex
status:
  configuration:
    generatedName: ""
